language: objective-c
xcode_project: TestSDK.xcodeproj
xcode_scheme: TestSDK
osx_image: xcode7.2
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - secure: l1LXobJf3jUi//HZ4KgKiftkELHjYNII8SMOWSN6+8ItcQEqZArtxw5TqoBH0ciV657vwlgqBKOG2egkQD6PHpX4j+H5RQpQ3K6r806ViF0UOm0m/2omCwmr5Ady67HYNRddnygcM5KtBSFOq48SMkx+pgiB3hGiBxex8rsxLGTg8v5l74j3iXVaiNM3u+Y4lgcY12E+RZqCnjCrgsGEnqkRZpE9nDbgxYGIgxmhIkydw4VSybfD6jNx97ORZyDg+mqL04PTpictV/iT1hrTHNnjKTmC7Q0Sy9bHqP4Rgr5d7PH6k55Excg4xg8RfXjP53+JT264+OJwptaK1OW+GMG6ZdpKzhbJc5pmyzAzXxsc3lVKLSdVxdJ/2eg8DyBD8smNBKdzZnv5y8mNkKLiqxiQOb+TK4s5ZAeg0ag2udwgUxIa2QJgl200mT7P140A2Zc++zYk/gCMTRWBtn+nTRPIOJPRKGkJJ2mrkUYNlGKwAJ0U5MAERrwUd52AButMdTHj8FDCe35dfscy2ouYT6xXrgCptO9epkD7sfUNUKEnPYZ1kI1p+DsDTTRVszZqAI/KNjJo5wThLqfUupGdG5xIIviMd1vnTj97W616evAxyO24cYf/+oSu9mWK9Dg0nJtqH8PQefMphaO13+K06iv+0KyfZYXNSQCgu/ui0AY=
  - APP_NAME="TestSDK"
  - 'DEVELOPER_NAME="iPhone Developer: Kristof Liliom (6L32HR3BL9)"'
  - PROFILE_NAME="TestSDK"
  - secure: jXTNxxdrZ94bddQ57sabXisoX3X84ii/kIHDQZ/iRaVkdFruLXax27024cC5M4uWQiDs1zvjgw+5vLQttF6dE/EpQ8aequkAKqz4PgEd+YFYutTdrC7erMvD82/tPuw0vHIkLfsD2BQsK+rBs/WdEwFGsYzAoMHC9punFA4LV2CE3ThztuX6lfuCcxvs83s3aL9a4nVsZucrdtr3jcxRxL5wj09eWyvE0d/175n3dfviHv/PXOePE3D9wSrWk26eKvCA/lbHXIrTdHAYg6mu9oIqKeJzXrK8AqG45MH+Zf3b6xDe0cznmE1/1owIAljO/oE2yd+liztDf+i1Qrcomk9Y79kwaScgie19DPNyTZnWF7xgMiM8MUqov2GYiFER+g6HBVYN+51Gi0C7tEZuBKhBM4aytn4fXs2bKhXVrXIPRSTyB9BRv4oQQ0Gb9B0PZiifk/tm1kf3vjug9JIyXAZk8oAuZwqfoESOL/MNPo+5o/3SXsWl3ULY4xHN1Q2IlAfj+OUqF5wS3MlIcZVjpxQDyQLHyA0k2JmdMjZIeFjXAVO1Jv2unhyCNSewd5sJsjgeDVHF51QDGhgBquWzUw+1txQkQ6zkE0tc/sJvKZldrd3cfpgmPaHAiCeI2QY2XMe+Q7KoF5CenR7A+746m9mSK9zUDFr6Mi6bcYcznjU=
before_script:
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/profile/TestSDK.mobileprovision.enc -d -a -out scripts/profile/TestSDK.mobileprovision
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.cer.enc -d -a -out scripts/certs/dist.cer
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/certs/dist.p12.enc -d -a -out scripts/certs/dist.p12
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/id_rsa.enc -d -a -out scripts/id_rsa
script:
  - ./scripts/add-key.sh
  - xctool test -project TestSDK.xcodeproj -scheme TestSDK -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -project TestSDK.xcodeproj -scheme TestSDK -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
  - xctool -project TestSDK.xcodeproj -scheme TestSDK -sdk iphonesimulator -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
after_success:
  - git clone https://liliomk@github.com/kovacsi/testrepo.git build-repo
  - cd build-repo
  - rm -rf TestSDK.framework
  - cp -R ../build/Release-iphoneos/TestSDK.framework ./
  - lipo ../build/Release-iphoneos/TestSDK.framework/TestSDK ../build/Release-iphonesimulator/TestSDK.framework/TestSDK -create -output TestSDK.framework/TestSDK
  - git add --all TestSDK.framework
  - git commit -m "$(cd ../ &&  git rev-parse HEAD)"
  - ssd-add -K scripts/id_rsa
  - git push origin master
  - ssd-add -K -d scripts/id_rsa
  - cd ..
  - rm -rf build-repo
after_failure:
 - cat -n ~/Library/Logs/scan/*
 - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
after_script:
  - ./scripts/remove-key.sh
