language: objective-c
xcode_project: TestSDK.xcodeproj
xcode_scheme: TestSDK
osx_image: xcode7.3
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
script:
  - set -o pipefail
  - xcodebuild clean build -target TestSDK -configuration Debug -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild clean build -target TestSDK -configuration Debug -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO 
  - xcodebuild clean build -target TestSDK -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild clean build -target TestSDK -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xcodebuild clean -scheme TestSDK -destination 'platform=iOS Simulator,name=iPhone 4s' test
after_failure:
 - cat -n ~/Library/Logs/scan/*
 - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
