language: objective-c
xcode_project: TestSDK.xcodeproj
xcode_scheme: TestSDK
osx_image: xcode7.2
sudo: false
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - APP_NAME="TestSDK"
  - PROFILE_NAME="TestSDK"
  - secure: jXTNxxdrZ94bddQ57sabXisoX3X84ii/kIHDQZ/iRaVkdFruLXax27024cC5M4uWQiDs1zvjgw+5vLQttF6dE/EpQ8aequkAKqz4PgEd+YFYutTdrC7erMvD82/tPuw0vHIkLfsD2BQsK+rBs/WdEwFGsYzAoMHC9punFA4LV2CE3ThztuX6lfuCcxvs83s3aL9a4nVsZucrdtr3jcxRxL5wj09eWyvE0d/175n3dfviHv/PXOePE3D9wSrWk26eKvCA/lbHXIrTdHAYg6mu9oIqKeJzXrK8AqG45MH+Zf3b6xDe0cznmE1/1owIAljO/oE2yd+liztDf+i1Qrcomk9Y79kwaScgie19DPNyTZnWF7xgMiM8MUqov2GYiFER+g6HBVYN+51Gi0C7tEZuBKhBM4aytn4fXs2bKhXVrXIPRSTyB9BRv4oQQ0Gb9B0PZiifk/tm1kf3vjug9JIyXAZk8oAuZwqfoESOL/MNPo+5o/3SXsWl3ULY4xHN1Q2IlAfj+OUqF5wS3MlIcZVjpxQDyQLHyA0k2JmdMjZIeFjXAVO1Jv2unhyCNSewd5sJsjgeDVHF51QDGhgBquWzUw+1txQkQ6zkE0tc/sJvKZldrd3cfpgmPaHAiCeI2QY2XMe+Q7KoF5CenR7A+746m9mSK9zUDFr6Mi6bcYcznjU=
before_script:
  - openssl aes-256-cbc -k "$ENCRYPTION_SECRET" -in scripts/id_rsa.enc -d -a -out scripts/id_rsa
script:
  - set -o pipefail
  - ./scripts/update-version.sh
  - xctool test -project TestSDK.xcodeproj -scheme TestSDK -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
  - xctool -project TestSDK.xcodeproj -scheme TestSDK -sdk iphoneos -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
  - xctool -project TestSDK.xcodeproj -scheme TestSDK -sdk iphonesimulator -configuration Release OBJROOT=$PWD/build SYMROOT=$PWD/build ONLY_ACTIVE_ARCH=NO 'CODE_SIGN_RESOURCE_RULES_PATH=$(SDKROOT)/ResourceRules.plist'
after_script:
  - ./scripts/deploy.sh
after_failure:
 - cat -n ~/Library/Logs/scan/*
 - cat -n $TMPDIR/com.apple.dt.XCTest-status/Session*.log
 - cat -n ~/Library/Logs/DiagnosticReports/xctest*.crash
