language: objective-c
xcode_project: TestSDK.xcodeproj
xcode_scheme: TestSDK
osx_image: xcode7.3
script:
  - set -o pipefail
  - xcodebuild clean build -target TestSDK -configuration Debug -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild clean build -target TestSDK -configuration Debug -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO 
  - xcodebuild clean build -target TestSDK -configuration Release -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
  - xcodebuild clean build -target TestSDK -configuration Release -sdk iphonesimulator ONLY_ACTIVE_ARCH=NO
